### ISSUE TITLE
make pypi to upload to PYPI

### ISSUE THREAD

**Issue by brunobord** [novafloss/workalendar#133]
- add a makefile target to correctly upload to PYPI,
- allow using a different location (to use your own localshop / devpi mirror)

**Comment by Natim** [comment]
Would you guys use zest.releaser?

Here is the release flow we are using in most projects: http://kinto.readthedocs.io/en/stable/community.html#how-to-release

**Comment by brunobord** [comment]
zest.releaser is fine, and I'm using it (partially), but... its commit messages are dull (IMHO) and there's no way (apparently) to configure these messages - I personally dislike the "preparing release blah", which **IS** the release commit message

I'm using "prerelease" (and rewrite the commit message), and eventually "postrelease", but never "release + upload".
I prefer to do the upload myself, using the options I want for the PyPI/localshop I'm connected to (wheel or no wheel? binary dist or no binary dist? etc).

Just having a makefile target here would just be fine for me, kinda like a "remote control" I could eventually adapt to my specific needs when I'm not uploading on PYPI. But never-ever using the fullrelease subcommand.

**Comment by Natim** [comment]
It is because you do not have yet a review process for your releases (Reviewing the changelog for instance)

**Comment by brunobord** [comment]
mmmm... using "prerelease" in a branch and "release" in master... interesting.

**Comment by brunobord** [comment]
done and released
