### ISSUE TITLE
The europe.py file starts to be quite big, should we start splitting calendars?

### ISSUE THREAD

**Issue by Natim** [novafloss/workalendar#135]
I think a file per country could make it easier to maintain.

europe.py → europe/___init__.py, europe/estonia.py, europe/france.py, europe/swiss.py, etc...

**Comment by brunobord** [comment]
good idea

**Comment by Natim** [comment]
I am starting the work here: https://github.com/novafloss/workalendar/pull/136
But I feel like usa.py and core.py might need to have the same treatment.

**Comment by brunobord** [comment]
>  But I feel like usa.py and core.py might need to have the same treatment.

AFAICT, usa.py won't evolve, since all the US states are in, and, except if global geopolitics changes happen, there won't be new states. Maybe, at some point, if Asian calendars are incoming, we may have to split (too) big modules

**Comment by Natim** [comment]
Does it means that I do not need to split usa.py and core.py ?

**Comment by brunobord** [comment]
@Natim for the "usa.py" I don't see the point. for the "core.py", I don't know for sure, but I wouldn't do it in this PR, maybe in another, when #135 is closed.

**Comment by brunobord** [comment]
merged, thanks a lot.
