### ISSUE TITLE
Put back the tests in the package

### ISSUE THREAD

**Issue by brunobord** [novafloss/workalendar#144]
it looks like they don't need to be ignored, since packagers can use them to test the python package before wrapping it into a .deb, for example

(am I right, @natim?)

**Comment by Natim** [comment]
Yes I think it is best to ship the tests with the package.

**Comment by Natim** [comment]
Now that the decision have been taken I can file a PR about it if you want,

**Comment by brunobord** [comment]
@natim nah, don't worry ; in fact this issue shouldn't be here, I just need to take care of it inside #141

**Comment by brunobord** [comment]
done in #141
