### ISSUE TITLE
Good Friday is Czech holiday from 2016

### ISSUE THREAD

**Issue by Birion** [novafloss/workalendar#148]
In 2016, Czech Republic added Good Friday as an official public holiday.

https://www.cnb.cz/en/public/media_service/schedules/media_svatky.html

**Comment by brunobord** [comment]
oh! thank you for the information. as I understand, the "Good Friday" holiday will also be a holiday in the future years, do you confirm it?

**Comment by Birion** [comment]
Yes, it's official holiday from 2016 onwards.

**Comment by brunobord** [comment]
thx. working on a patch, I'll make a bugfix release right after it.

**Comment by brunobord** [comment]
closed by #149

**Comment by brunobord** [comment]
I've made a 0.8.0 release with this fix. You're free to upgrade, now ;op
