### ISSUE TITLE
Germany 2017: Reformation Day is valid in all states

### ISSUE THREAD

**Issue by zdenyv** [novafloss/workalendar#150]
The Reformation Day in the next year 2017 is public holiday in whole Germany. 
In the other years it is valid only in Brandenburg, MecklenburgVorpommern, Saxony, SaxonyAnhalt, Thuringia (as it is defined now correctly).
https://www.welt.de/regionales/nrw/article143064981/Reformationstag-2017-wird-auch-in-NRW-ein-Feiertag.html

**Comment by brunobord** [comment]
oh! thanks a lot for the heads-up.
I'll plan to work on this as quick as possible, to make a release right after it.

**Comment by Natim** [comment]
\o/

**Comment by brunobord** [comment]
@zdenyv you can now upgrade to ``workalendar==0.8.1`` -- https://pypi.python.org/pypi/workalendar/0.8.1
enjoy

**Comment by zdenyv** [comment]
Cool! Thank you for such a quick fix! You are amazing team!

**Comment by brunobord** [comment]
> Cool! Thank you for such a quick fix! You are amazing team!

That was easy, so I thought it'd be nice to make it fast ;o)
