### ISSUE TITLE
2016 Christmas is on Sunday

### ISSUE THREAD

**Issue by shadowleaves** [novafloss/workalendar#171]
and 12/26/2016 (Monday) is a holiday in observation of X'mas. workalendar 1.0.0 as of now still doesn't correctly identify that. thanks

**Comment by Natim** [comment]
@shadowleaves do you know for which countries? It is not the case in France for instance.

**Comment by shadowleaves** [comment]
for the United States, Germany, Italy, Dec 26th 2016 is a holiday observing X'mas
for UK, Dec 27th 2016 is a holiday (26th is Boxing day, 27th is observing X'mas)

i'll add more as I find out...

**Comment by brunobord** [comment]
* For the USA, it's [covered by this class](https://github.com/novafloss/workalendar/blob/master/workalendar/usa.py#L54-L84). The thing is that every State has its own rules, can you please provide a State use-case where this "26th december" is missing?
* For Germany, it's handled via this variable in the core Germany calendar: https://github.com/novafloss/workalendar/blob/master/workalendar/europe/germany.py#L18 ; every Länder has this day as a holiday,
* Same for Italy: https://github.com/novafloss/workalendar/blob/master/workalendar/europe/italy.py#L18
* In UK also, including a complex (but robust) function to compute the Boxing day/ XMas day shift: https://github.com/novafloss/workalendar/blob/master/workalendar/europe/united_kingdom.py#L38-L47

So, correct me if I'm wrong: in which calendar did you happen to find a bug?

**Comment by shadowleaves** [comment]
@brunobord 

version 1.0.0 of workalendar:
`
from workalendar.usa import UnitedStates
from datetime import datetime

cal=UnitedStates()
print cal.is_holiday(datetime(2016,12,26))
`

this will give a False output, where as Dec 26th 2016 is indeed a federal holiday (observing X'mas)

**Comment by brunobord** [comment]
@shadowleaves ah, there you have one! something interesting to look after ; thanks a lot!
/me dives in debugging mode

**Comment by brunobord** [comment]
quick question: according to wikipedia, I see that 

> When a holiday occurs on Saturday or Sunday, that holiday is shifted to either Friday or Monday.
> -- https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States

But, in some states, it looks like it's not a rule set in stone:

> Michigan: December 24 - Christmas Eve (if Christmas Eve falls on Sunday as it does in 2017, December 22 is the observed holiday)

or

> West Virginia: Note: Christmas Eve and New Years Eve are half day holidays and are not shifted if they fall on Saturday or Sunday.

I think the bug is a bit bigger than I first thought about, and we may need to completely revamp the ``usa.py`` module and its tests.

Again, thank you for the report ; we'll try to work on it as quick as we can (although it will probably take some time).

**Comment by shadowleaves** [comment]
Christmas Eve is not a Federal holiday and thus each state might have different rules. but the issue is not Christmas Eve here. This bug concerns the Christmas Day (12/25), which is a U.S. Federal holiday, and it falls on Sunday in 2016, and the following Monday (12/26) is made a holiday, and all states in the US observe that.

**Comment by brunobord** [comment]
@shadowleaves you're right... but my point here is that every "fixed" day in the USA may be shifted a day before or a day after ; or maybe not shifted in some states, etc.

The good news here is that, a few years after my first pass on the USA public holidays, the wikipedia page has been extensively improved, and it'll help a lot to fix this ugly bug.

(always look on the bright side of life -whistle- )

**Comment by brunobord** [comment]
closing, since workalendar 2.0.0 is now available via PyPI: https://pypi.python.org/pypi/workalendar/2.0.0

enjoy!
