### ISSUE TITLE
Corrections to Brazil

### ISSUE THREAD

**Issue by Skippern** [novafloss/workalendar#187]
I noticed that Easter is not returned in Brazil, looking at the source code `america.py`, I see it is placed in BrazilSaoPauloCity, the same with Carnaval. 

I am listing below all state holidays, and a few municipalities within Espírito Santo.

# Acre (AC)
```python
(1, 23, u"Dia do evangélico")
(6, 15 u"Aniversário do Acre")
(9, 5, u"Dia da Amazônia")
(11, 17, u"Assinatura do Tratado de Petrópolis")
```
# Alagoas (AL)
```python
(6, 24, u"São João")
(6, 29, u"São Pedro")
(9, 16, u"Emancipação política de Alagoas")
(11, 20, u"Consciência Negra")
```
# Amapá (AP)
```python
(3, 19, u"Dia de São José")
(7, 25, u"São Tiago")
(10, 5, u"Criação do estado")
(11, 20, u"Consciência Negra")
```
# Amazonas (AM)
```python
(9, 5, u"Elevação do Amazonas á categoria de província")
(11, 20, u"Consciência Negra")
(12, 8, u"Dia de Nossa Senhora da Conceição")
```
# Bahia (BA)
```python
(7, 2, u"Independência da Bahia")
```
# Ceará (CE)
```python
(3, 19, u"São José")
(3, 23, u"Data Manga do Ceará")
```
# Distrito Federal (DF)
```python
(4, 21, u"Fundação de Brasília")
(11, 30, u"Dia do Evangélico")
```
#  Espírito Santo State (ES)
```python
(10, 28, u"Dia do Servidor Público")
```
# Goiás (GO)
```python
(10, 28, u"Dia do Servidor Público")
```
# Maranhão (MA)
```python
(7, 28, u"Adesão do Maranhão á independência do Brasil")
(12, 8, u"Dia de Nossa Senhora da Conceição")
```
# Mato Grosso (MT)
```python
(11, 29, u"Consciência Negra")
```
# Mato Grosso do Sul (MS)
```python
(10, 11, u"Criação do estado")
```
# Pará (PA)
```python
(8, 15, u"Adesão do Grão-Pará á independência do Brasil")
```
# Paraíba (PB)
```python
(8, 5, u"Fundação do Estado")
```
# Pernambuco (PE)
```python
(6, 24, u"São João")
```
# Piauí (PI)
```python
(3, 13, u"Dia da Batalha do Jenipapo")
(10, 19, u"Dia do Piauí")
```
# Rio de Janeiro (RJ)
```python
MOVING = [ u"Carnaval", u"Dia do Comércio" ]
(4, 23, u"Dia de São Jorge")
(10, 28, u"Dia do Funcionário Público")
(11, 20, u"Zumbi dos Palmares")
(12, 8, u"Dia de Nossa Senhora da Conceição)
```
# Rio Grande do Norte (RN)
```python
(6, 29, u"Dua de São Pedro")
(10, 3, u"Mártires de Cunhaú e Uruaçuu")
```
# Rio Grande do Sul (RS)
```python
(20, 9, u"Revolução Farroupilha")
```
# Rondônia (RO)
```python
(1, 4, u"Criação do estado")
(6, 18, u"Dia do Evangélico")
```
# Roraima (RR)
```python
(10, 5, u"Criação de Roraima")
```
# Santa Catarina (SC)
```python
(8, 11, u"Criação da capitania, separando-se de SP")
```
# São Paulo (SP)
```python
MOVING = [ u"Sexta-feira da Paixão" ] # Good friday
(7, 9, u"Revolução Constitucionalista de 1932")
```
# Sergipe (SE)
```python
(7, 8, u"Autonomia política de Sergipe")
```
# Tocantins (TO)
```python
(1, 1, u"Instalação de Tocantins")
(9, 8, u"Nossa Senhora da Natividade")
(10, 5, u"Criação de Tocantins")
```
# City of Vitória / ES
List decorated by Municipal Law
```python
MOVING = [ u"Paixão do Cristo", u"Corpus Christie" ] # Good friday, Corpus Christie
(4, 24, u"Nossa Senhora da Penha") # Our Lady of Pain?
(9, 8, u"Nossa Senhora da Vitória") # Our Lady of Vitória
```
# City of Vila Velha / ES
```python
(5, 23, u"Colonização do Solo Espírito-santense")
```
# City of Viana / ES
```python
(7, 8, u"") # No description
(7, 23, u"") # No description
(8, 28, u"") # No description
(9, 8, u"") # No description
(12, 8, u"") # No description
```
# City of Cariacica / ES
```python
MOVING = [ u"Paixão de Cristo", u"Corpus Christie" ] # Good friday, Corpus Christie
(4, 13, u"Nossa Senhora da Penha")
(6, 24, u"São João Batista / Aniversãrio de Cariacica")
```
# City of Guarapari / ES
```python
(6, 29, u"São Pedro")
(9, 19, u"Emancipação de Guarapari")
(11, 29, u"Consciência Negra")
(12, 8, "Nossa Senhora Conceição")
```
# City of Serra / ES
```python
MOVING = [ u"Carnaval", u"Quarta-feira de cinzas", u"Paixão de Cristo" ] # Carnaval (Monday & Tuesday), Ash Wednesday, Good Friday
(6, 29, u"São Pedro")
(12, 8, u"Nossa Senhora Conceição")
(12, 26, u"Dia do Serrano")
```

**Comment by brunobord** [comment]
hello and thank you for this report.... Are all these days **observed** holidays? that is to say "non-working days"?

**Comment by Skippern** [comment]
All of these mentioned are "non-working days".

When mentioning this, I was just starting to look for functions for school holidays or academic holidays as well, as I use this for bus routes, and some bus routes have foot notes like (**S**, **Only on School days**), but I guess that will have to include a whole new variable in addition to the existing.

For the RJ `Dia do Comércio`, I do not know the rules for it, since I do not deal directly with RJ state, but can maybe investigate into it.

I have observed deviations from the list I have posted, but this list is as far as I know all the official days, or derived from official sources.

**Comment by brunobord** [comment]
Ok, so I guess that we're going to need a ``brazil.py`` module pretty soon.
stay tuned!

**Comment by Skippern** [comment]
With a little investigation I can give you the rest of the 78 municipalities of `Espírito Santo` state, but it will be too much work to include all ~5500 Brazilian municipalities. Also I do not know if they will be needed any time soon. All the municipalities I have mentioned are used in my current project.

**Comment by brunobord** [comment]
> a thousand miles journey starts with one step

**Comment by brunobord** [comment]
next question is: are all these holidays *fixed* holidays, or may they vary?
in other ways: do we have a reference document to explain how to compute these holidays?

**Comment by Skippern** [comment]
All of those I have stated with a fixed date are _fixed_, what I have placed as `MOVING = []`

Carnaval is 47 days before easter, I noticed it was already included in `SaoPauloCity`, you can probably move that to `Brazil` and use an `include_carnaval` statement as not all cities officially recognises it as a holiday

RJ state have a `Dia do Comércio` that are moving, I will need to look up definition for you.

**Comment by Skippern** [comment]
According to [this link](http://copacabana.com/eventos/dia-do-comercio), `Dia do Comércio` in RJ state is on the 3rd Monday in October.

**Comment by brunobord** [comment]
@Skippern:

I'm currently working on these Brazil calendars, as you can see, and I've got an issue with "Rio de Janeiro".
According to the [following wikipedia page - https://pt.wikipedia.org/wiki/Feriados_no_Brasil#Rio_de_Janeiro](https://pt.wikipedia.org/wiki/Feriados_no_Brasil#Rio_de_Janeiro) there's no such holidays:

* YYYY-10-28: Dia do Funcionário Público,
* YYYY-11-20: Zumbi dos Palmares,
* YYYY-12-8: Dia de Nossa Senhora da Conceição,

Also, it looks like the "Dia do Comércio" is a holiday for shops and civil-construction workers.

1. could you confirm me that I shall include those 3 missing holidays? (and confirm me that wikipedia is wrong?)
2. Could you confirm me that I shall include the "Dia do Comércio" in the Rio de Janeiro calendar?

**Comment by brunobord** [comment]
oh, about the *"Zumbi dos Palmares"*, it looks like it's the same as "Dia da Consciência Negra"... rephrasing my question for this one: *Which label shall I use?"

**Comment by Skippern** [comment]
My source might be incomplete, so you can include the missing days from wikipedia

Zumbi and Conceição Negra is the same, though I think Rio use the term Zumbi. I am not 100% certain what term is used where

Dia do Comércio was mentioned in my source, though I think it might not be observed equally by private sector and government

**Comment by brunobord** [comment]
> My source might be incomplete, so you can include the missing days from wikipedia

ah, it's the other way around: Wikipedia doesn't mention the RJ days you're providing in the issue.

**Comment by Skippern** [comment]
Would guess Wikipedia incomplete too

**Comment by brunobord** [comment]
All right, i'll go on like this until "some carioca" complains about the wrong dates ;o)
thx for the clarification.

**Comment by Skippern** [comment]
No problem, I might as well add more as I need, those suggested currently covers my needs and some

**Comment by brunobord** [comment]
The version 1.2.0 is now published: you can install it via pip! Closing. Don't hesitate to open an issue or a PR to fix eventual bugs or suggest improvements
