### ISSUE TITLE
get_weekend_days on base Calendar class

### ISSUE THREAD

**Issue by nedlowe** [novafloss/workalendar#189]
Hi,

get_weekend_days raises a NotImplementedError on the base class, but a sensible default could be provided using the method from WesternCalendar (which returns self.WEEKEND_DAYS).

For example, Qatar has WEEKEND_DAYS correctly set to (FRI, SAT) - but fails since it doesn't derive from WesternCalendar.  Obviously one could copy the WesternCalendar implementation across, but surely something like:

```
if self.WEEKEND_DAYS:
     return self.WEEKEND_DAYS
else:
    raise NotImplementedError
```

on the base class makes more sense (and then remove the WesternCalendar method)?

I'm happy to throw out a PR if this makes sense.

**Comment by Natim** [comment]
Yes please go ahead.

**Comment by nedlowe** [comment]
Done, thank you.
