### ISSUE TITLE
Inherit state holidays in Brazil

### ISSUE THREAD

**Issue by Skippern** [novafloss/workalendar#199]
Shouldn't the cities inherit the state holidays for Brazil? I see São Paulo city inherits São Paulo state, while Guarapari, Vila Velha, Serra, Cariacica and Vitoria inherits Brazil... I would guess prudent for these to inherit Espírito Santo.

**Comment by brunobord** [comment]
are you positive about this? If so, I can fix this very quickly.

**Comment by Skippern** [comment]
Just noticed the odd difference between the newly added cities and São Paulo City. Since I live in the region of these newly added cities I can have it verified, but will need some time. I might need a reminder though.

Aun Johnsen

**Comment by brunobord** [comment]
> I might need a reminder though.

I'll keep this in mind. :o)

**Comment by brunobord** [comment]
@Skippern Any news?

**Comment by Skippern** [comment]
Calm your horses, I am on travel ;) I will try look at it shortly though

Aun Johnsen

**Comment by brunobord** [comment]
fair enough ;o) -- will reset my reminder to "next week" ;o)

**Comment by brunobord** [comment]
@Skippern back from your travel?

**Comment by Skippern** [comment]
63 days to go

**Comment by brunobord** [comment]
@Skippern ouch... Do you know if I can ping a Brazilian Pythonista (or maybe not a developer, that could be someone with enough knowledge about legal holidays...) that could confirm this issue, then? If there's a true bug, I'd like to solve it and make a fix release quickly....

**Comment by Skippern** [comment]
Probably

**Comment by brunobord** [comment]
I've worked this out with a collegue that has Brazilian connections: indeed, the Brazilian city calendars should have Federal days + State days + City days.
I'll fix ASAP.

**Comment by brunobord** [comment]
[fixed and available in the v1.3.0 release](https://github.com/novafloss/workalendar/releases/tag/1.3.0)
