### ISSUE TITLE
Since 04.2017 good friday is work free holiday in Hungary

### ISSUE THREAD

**Issue by mariusz-korzekwa** [novafloss/workalendar#203]
Hi, Since 14.04.2017 Good Friday is work-free holiday in Hungary
http://hungarytoday.hu/news/official-good-friday-voted-become-hungarys-eleventh-public-holiday-89938

Can you add it?

**Comment by brunobord** [comment]
yup, it's possible. I'll add it ASAP, thanks for the opened issue

**Comment by brunobord** [comment]
merged

**Comment by brunobord** [comment]
[fixed and available in the v1.3.0 release](https://github.com/novafloss/workalendar/releases/tag/1.3.0)
