### ISSUE TITLE
Black Friday & Cyber monday

### ISSUE THREAD

**Issue by eyaltrabelsi** [novafloss/workalendar#230]
Did you not include these on purpuse ? i dont mind writing a pull request and fix it

**Comment by brunobord** [comment]
Are these legal holidays?

**Comment by eyaltrabelsi** [comment]
No thata why I asked before writing code i think one can leavrage this cool repo uaing formal plus informal holidays.... it can be the base to very cool udfs

**Comment by brunobord** [comment]
Workalendar is focused on legal public holidays. And I can tell you that this task is already complicated enough, so I don't think I would try to add non-legal holidays to my this library.

FYI, the US calendars are currently being rewritten/fixed/refactored in this PR: https://github.com/novafloss/workalendar/pull/229
What you call "Black Friday" is usually called "Thanksgiving Friday" and is included as soon as they're legally declared a public holiday in the corresponding calendars. See it here: 

* https://github.com/novafloss/workalendar/blob/171-usa-holidays-fix/workalendar/usa/core.py#L22-L23
* https://github.com/novafloss/workalendar/blob/171-usa-holidays-fix/workalendar/usa/core.py#L131-L136
* https://github.com/novafloss/workalendar/blob/171-usa-holidays-fix/workalendar/usa/core.py#L279-L282

For example, the [California calendar](https://github.com/novafloss/workalendar/blob/171-usa-holidays-fix/workalendar/usa/california.py) is including it.

As a consequence, I think it'd be very easy to build a custom class in your project, derived from the ``UnitedStates`` core class:

```python
from workalendar.usa import UnitedStates
from datetime import timedelta
class MyCustomState(UnitedStates):
    include_thanksgiving_friday = True
    thanksgiving_friday_label = "Black Friday"
    def get_variable_days(self, year):
        days = super(MyCustomState, self).get_variable_days(year)
        friday, _ = self.get_thanksgiving_friday(year)
        days.append(
            (friday + timedelta(days=3), "Cyber Monday")
        )
        return days
```

Of course, you'll have to wait for the next release to use these features, but if you can't wait, you can still copy the required code to fit your needs...

**Comment by brunobord** [comment]
will close as "wontfix", since these "non-legal public holidays" will not be included in the library.
but don't despair: we're always looking for contributions and any suggestion will be examined!
