### ISSUE TITLE
Reconciliation Day Australian Capital Territory

### ISSUE THREAD

**Issue by rodxavier** [novafloss/workalendar#251]
Starting 2018, Family and Community Day will be removed from ACT holidays and will be replaced by Reconciliation Day.

Reconciliation Day is based on the following rules:
- It is to be celebrated on 27th May
- If 27th May is not a Monday, the following Monday

http://www.sbs.com.au/nitv/nitv-news/article/2017/09/19/act-first-recognise-reconciliation-day-public-holiday
http://www.legislation.act.gov.au/b/db_56690/current/pdf/db_56690.pdf

**Comment by brunobord** [comment]
closed by #250.
